version: "3"

services:
  mongodb:
    container_name: "db"
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="nest"
    expose:
      - 27017

  api:
    container_name: "api"
    build: .
    environment:
      - DB_HOST=db
    ports:
      - 3000:3000
    depends_on:
      - mongodb
